### ISSUE TITLE
Would a Slack channel #transducers benefit many?

### ISSUE THREAD

**Issue by JeffreySarnoff** [tkf/Transducers.jl#198]
I'd create it with your approval.

**Comment by tkf** [comment]
Hi, thanks for your interest. If the idea is to create a place for people interested in transducers, I think that's a great idea.

But I only occasionally check Julia slack so I don't think _I_ can answer questions regularly there. I also personally prefer that the discussions are permanently accessible in open places like GitHub / Discourse.
