### ISSUE TITLE
mapfoldl signature

### ISSUE THREAD

**Issue by jw3126** [tkf/Transducers.jl#2]
In julia `1.0` init is a keyword, argument, not a positional argument. So maybe it should also be a keyword argument in the transducer case?
```julia
julia> mapfoldl(identity, =>, 1:3, init=0)
((0=>1)=>2) => 3

julia> mapfoldl(identity, =>, 0, 1:3)
ERROR: MethodError: no method matching mapfoldl(::typeof(identity), ::Type{Pair}, ::Int64, ::UnitRange{Int64})

```

**Comment by tkf** [comment]
Hi, thanks for reviewing this package!

Yeah, that's a good point.  I think I'll make `mapfoldl` and `foldl` more `Base`-compatible.

It looks like normal `mapfoldl` uses `Base.reduce_empty(op, T)`to determine an appropriate identity element.  I think I can use it (actually I've done a similar trick with `Scan` manually already so it'd simplify the code).

```julia
julia> mapfoldl(identity, *, Int[])
1

julia> Base.reduce_empty(*, Int)
1

julia> mapfoldl(identity, *, Matrix{Float64}[])
ERROR: MethodError: no method matching one(::Type{Array{Float64,2}})
Closest candidates are:
  one(::Missing) at missing.jl:83
  one(::BitArray{2}) at bitarray.jl:400
  one(::Type{T<:Number}) where T<:Number at number.jl:297
  ...
Stacktrace:
 [1] reduce_empty(::typeof(*), ::Type) at ./reduce.jl:229
 [2] mapreduce_empty(::typeof(identity), ::Function, ::Type) at ./reduce.jl:251
...
```

**Comment by jw3126** [comment]
If you like I could try to do that change in a PR.

**Comment by tkf** [comment]
That'd be great!
