### ISSUE TITLE
trouble with TeeZip

### ISSUE THREAD

**Issue by atthom** [tkf/Transducers.jl#214]
I have trouble to apply processing with TeeZip transducer.

I am unable to run the @doc example:

julia> collect(TeeZip(Filter(isodd) |> Map(x -> x + 1)), 1:5)
ERROR: MethodError: no method matching Transducers.PrivateState(::Int64, ::Array{Union{},1})

I can run other transducers.
I am on Julia 1.3.0 and Transducers.jl v0.4.3

**Comment by tkf** [comment]
I can't reproduce the bug. Maybe update Transducers? It's v0.4.17 now.

**Comment by atthom** [comment]
Thanks! It was just that.
