### ISSUE TITLE
define something for `halve(::AbstractDict)`?

### ISSUE THREAD

**Issue by ExpandingMan** [tkf/Transducers.jl#258]
You can't currently do `tcollect` over an `AbstractDict` because there is no method for `halve(::AbstractDict)`.  One could do `collect(dict)`, but I'm wondering if it's better to define something that doesn't allocate the new array?

**Comment by tkf** [comment]
Yeah, it'd be nice to have `halve` for `AbstractDict`.  I'm using `halve` as a building block to easily support something like dictionaries.

To make it more efficient than "`collect` first" approach, I think it needs to be done per-type basis and has to know about the implementation details.  For this reason, I'm kind of hoping that `halve` is implemented by the implementer of each dictionary subtype.  It means that I need to try to upstream SplittablesBase.jl to Base at some point though.
