### ISSUE TITLE
Incomplete GroupBy documentation

### ISSUE THREAD

**Issue by alecloudenback** [tkf/Transducers.jl#261]
The GroupBy doc description ends with a partial sentence, teasing an example that never follows:

> Group the input stream by a function key and then fan-out each group of key-value pairs to the reducing function rf. For example, if GroupBy is composed as follows

**Comment by tkf** [comment]
Actually, I wrote this as a whole paragraph:

https://github.com/tkf/Transducers.jl/blob/0c8944ac88d81168cd5e76ef9eb986b36081381d/src/library.jl#L1852-L1864

But maybe "as follows" sounds like the sentence ends there?  Maybe something like

> For example, if `GroupBy` is used as in:
> [...the first code block...]
> then the "function signatures" would be:
> [...the second code block...]

is better?

**Comment by waldyrious** [comment]
IMO just adding `:` after "follows" would resolve the ambiguity. But the reworded suggestion sounds good to me, too.

**Comment by tkf** [comment]
Thank you guys for helping me improve the documentation. I think #262 addresses this issue.

**Comment by alecloudenback** [comment]
I see - I was referring to the documentations index page, which didn't show the whole context that you referenced above:
![image](https://user-images.githubusercontent.com/711879/80166499-bd480a80-85a3-11ea-9060-5a667df86724.png)

Thanks for adding more clarity!

**Comment by tkf** [comment]
@alecloudenback Ah! Thanks a lot for pointing it out. I completely forgot how I generated the index page :)
