### ISSUE TITLE
No speedup for advertised eduction example

### ISSUE THREAD

**Issue by milesfrain** [tkf/Transducers.jl#44]
Following the example in the [0.3 announcement post](https://discourse.julialang.org/t/ann-transducers-jl-0-3-taking-zeros-seriously-type-stability-improvements-fusible-groupby-onlinestats-gpu-support-and-more/26873). Was hoping to see ~10x performance improvement.
Was there a regression with 0.4?

``` julia
(transduce) pkg> status
    Status `~/temp/transduce/Project.toml`
  [6e4b80f9] BenchmarkTools v0.4.3
  [28d57a85] Transducers v0.4.0

julia> itr = (y for x in 1:1000 for y in 1:x);

julia> @btime foldl(+, eduction(itr))
  222.099 μs (4 allocations: 96 bytes)
167167000

julia> @btime sum(itr)
  198.473 μs (1 allocation: 16 bytes)
167167000
```

**Comment by tkf** [comment]
So the new fix #45 makes it ~10x faster than 0.3 and so ~100x faster than the iterator.

**Comment by milesfrain** [comment]
Excellent! And record-setter for fastest bugfix I've experienced.
Wondering if benchmark testing should compare against non-transducer implementations and ensure a minimal level of performance improvement. This could also be a nice way for users to see the performance improvements on their systems.
I assume the PkgBenchmark judge is for comparing the same functions on the same hardware. Still helpful for catching this sort of regression though.

**Comment by tkf** [comment]
> Wondering if benchmark testing should compare against non-transducer implementations and ensure a minimal level of performance improvement.

I'm actually doing this in TransducersBenchmarksReports.jl: https://github.com/tkf/TransducersBenchmarksReports.jl/blob/master/docs/src/gemm.md#transducers-vs-manual-implementation

I haven't hooked it up Transducers.jl's CI as it's a bit tedious to set it up (compared to just calling `judge`).

> Still helpful for catching this sort of regression though.

Yep, I should have added it in the benchmark :)
