### ISSUE TITLE
Allow redefining isequal inside Unique ?

### ISSUE THREAD

**Issue by atthom** [tkf/Transducers.jl#51]
Base.unique allow redefinition of `isequal`.

>   unique(f, itr)
> 
>   Returns an array containing one value from itr for each unique value produced by f applied to elements of itr

```
julia> collect(unique(x-> x^2, [1, 1, 2, -1, 3, 3, 2]))
3-element Array{Int64,1}:
 1
 2
 3
```

with Unique it's not possible to do so:

```
julia> collect(Unique(x-> x^2), [1, 1, 2, -1, 3, 3, 2])
ERROR: MethodError: no method matching Unique(::var"##91#92")
```

**Comment by tkf** [comment]
Sounds like a good feature to have.
