### ISSUE TITLE
Distributed.jl-based reduce

### ISSUE THREAD

**Issue by tkf** [tkf/Transducers.jl#55]
Thread-based `reduce` is unsafe/scary to use especially when calling functions from external packages.  Using Distributed.jl would be much easier and safer in many cases.

**Comment by atthom** [comment]
I was wondering if there is any way to have parallelization of `mapfoldl`. Apparently it's on the roadmap :).
Have you considered https://github.com/JuliaParallel/Dagger.jl or https://github.com/invenia/Dispatcher.jl?
As Transducers can be seen as a DAG. It might be an easy path toward parallelization.

**Comment by tkf** [comment]
FYI, `reduce` implemented in Transducers.jl already supports thread-based parallelism. This issue is about adding process-based parallelism (which is much safer to use).

I've never used Dagger.jl or Dispatcher.jl but both seem to be about "model parallelism" rather than data parallelism which is what `reduce` is about. I think using Distributed.jl directly might be simpler.
